-- update Speaker table, add other proprieties
ALTER TABLE "Speaker" ADD COLUMN IF NOT EXISTS first_name VARCHAR(150);
ALTER TABLE "Speaker" ADD COLUMN IF NOT EXISTS last_name VARCHAR(150);
ALTER TABLE "Speaker" ADD COLUMN IF NOT EXISTS description VARCHAR(250);
ALTER TABLE "Speaker" ADD COLUMN IF NOT EXISTS Linkedln VARCHAR(150);
ALTER TABLE "Speaker" ADD COLUMN IF NOT EXISTS company VARCHAR(150);
ALTER TABLE "Speaker" ADD COLUMN IF NOT EXISTS email VARCHAR(150);


